version: '3'
services:
  postgres:
    build: ./postgresql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  app:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"